name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macOS-build:
    runs-on: macos-latest
    steps:
#      - uses: snickerbockers/cmake-configure@prerel1
      - uses: actions/checkout@v2
      - name: check directory location
        run: pwd
      - name: list files
        run: ls -laGh
      - name: mkdir build
        run: mkdir -p build
      - name: cd build
        run: cd build
      - name: check build location
        run: pwd
#      - name: run cmake
#        run: cmake ../
#      - name: list generated files
#        run: ls -laGh
#      - name: check directory location
#        run: pwd
#     - uses: actions/upload-artifact@v2
#       with:
#        name: macOS-x64
#        path: /Users/runner/work/sockety/sockety/build
