name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make clean
      run: make clean
    - name: make (all)
      run: make
    - name: check directory location
      run: pwd
    - name: list files
      run: ls -laGh
  
